name: Code Quality Checks

on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  codeQuality:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Check with eslint
        id: eslint-run
        run: |
          npm run lint
      - name: Build with Vite
        run: npm run build
